### ISSUE TITLE
Sort keys "ascending" parameter gets overriden

### ISSUE THREAD

**Issue by dmazurenko** [magicalpanda/MagicalRecord#1245] opened 2016-06-22 09:25 UTC
```
+ (NSFetchRequest *) MR_requestAllSortedBy:(NSString *)sortTerm ascending:(BOOL)ascending withPredicate:(NSPredicate *)searchTerm inContext:(NSManagedObjectContext *)context
{
    NSFetchRequest *request = [self MR_requestAllInContext:context];
    if (searchTerm)
    {
        [request setPredicate:searchTerm];
    }
    [request setFetchBatchSize:[self MR_defaultBatchSize]];

    NSMutableArray* sortDescriptors = [[NSMutableArray alloc] init];
    NSArray* sortKeys = [sortTerm componentsSeparatedByString:@","];
    for (__strong NSString* sortKey in sortKeys)
    {
        NSArray * sortComponents = [sortKey componentsSeparatedByString:@":"];
        if (sortComponents.count > 1)
          {
              NSString * customAscending = sortComponents.lastObject;
              ascending = customAscending.boolValue;
              sortKey = sortComponents[0];
          }

        NSSortDescriptor *sortDescriptor = [[NSSortDescriptor alloc] initWithKey:sortKey ascending:ascending];
        [sortDescriptors addObject:sortDescriptor];
    }

    [request setSortDescriptors:sortDescriptors];

    return request;
}
```

This method modifies initial `ascending` parameter for all other elements in the array. You can easily reproduce this by specifying `key:NO,anotherKey` and passing `YES` to ascending parameter in `MR_requestAllSortedBy`. The result sort descriptor will contain `ascending:NO` for `anotherKey`. 

To fix this you need to declare a local variable for custom `ascending` parameter and use it instead

**Comment by deanWombourne** [comment] 2016-07-30 13:38
Hey. If no-one else is looking at this it seems a nice easy one for me to get the hang of contributing to this library :)

**Comment by deanWombourne** [comment] 2016-07-30 14:02
Hey @dmazurenko - I can't reproduce this with a test :( Can you take a look at my PR and let me know what I've missed? 

Thanks.

**Comment by deanWombourne** [comment] 2016-07-30 14:07
Hey @dmazurenko - was being dense, I've worked out what I missed, and I think mr PR fixes it now :) Can you confirm please? 

Thanks.

**Comment by Coeur** [comment] 2019-06-21 17:08
Pull Request merged. Thank you @deanWombourne.

**Closed by Coeur** 2019-06-21 17:08 UTC

**Comment by deanWombourne** [comment] 2019-06-21 20:44
Awesome, thanks!
