### ISSUE TITLE
NSFetchedResultsControllerDelegate Methods Never Called

### ISSUE THREAD

**Issue by travisjbeck** [magicalpanda/MagicalRecord#946] opened 2015-01-22 00:01 UTC
I am creating a FRC with:

```
- (NSFetchedResultsController *)fetchedResultsController {
    
    if (_fetchedResultsController != nil) {
        return _fetchedResultsController;
    }
    
    NSManagedObjectContext *context = [NSManagedObjectContext MR_defaultContext];
    
    
    NSArray  *following = [[SessionManager getInstance].currentLoggedInUser.follows allObjects];
    NSDate *now = [NSDate date];

    NSPredicate *pred = [NSPredicate predicateWithFormat:@"account IN %@ && expiration > %@", following, now];
    _fetchedResultsController = [Post MR_fetchAllSortedBy:@"expiration"
                                                   ascending:YES
                                               withPredicate:pred
                                                     groupBy:nil
                                                    delegate:self
                                                    inContext:context];
    
    
    return _fetchedResultsController;
}

```
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSError *error;
    if (![[self fetchedResultsController] performFetch:&error]) {
        // Update to handle the error appropriately.
        NSLog(@"Unresolved error %@, %@", error, [error userInfo]);
        exit(-1);  // Fail
    }
```
and saving data with:
```
[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext){
                                        } completion:^(BOOL success, NSError *error) {
                                        }];
```

The FRC delegate methods are never called in my UIViewController and the table data is blank until I leave the view and come back or reload the app.

**Comment by Alydyn** [comment] 2015-01-22 01:29
Can you show how you create the context you use to create the FRC?

**Comment by travisjbeck** [comment] 2015-01-22 02:47
@Alydyn sorry, not sure if I understand..

**Comment by Alydyn** [comment] 2015-01-22 10:44
@travisjbeck ok I see you added it now.  What version of MR are you using?

**Comment by travisjbeck** [comment] 2015-01-22 16:13
I get the same thing in 2.2 and the current "develop" branch.

**Comment by travisjbeck** [comment] 2015-01-22 18:14
Some More Info.  I added NSManagedObjectContextDidSaveNotification to get some more info:

```
-(NSManagedObjectContext *)context
{
    if(!_context){
        
        _context = [NSManagedObjectContext MR_defaultContext];
    }
    return _context;
}


- (NSFetchedResultsController *)fetchedResultsController {
    
    if (_fetchedResultsController != nil) {
        return _fetchedResultsController;
    }
    
    NSArray  *following = [[SessionManager getInstance].currentLoggedInUser.follows allObjects];
    
    if(self.account){
        //only show the posts for the account that was given
        following = @[self.account];
    }
    
    NSDate *now = [NSDate date];

    NSPredicate *pred = [NSPredicate predicateWithFormat:@"account IN %@ && expiration > %@", following, now];
    NSFetchedResultsController *theFetchedResultsController = [Post MR_fetchAllSortedBy:@"expiration"
                                                   ascending:YES
                                               withPredicate:pred
                                                     groupBy:nil
                                                    delegate:self
                                                    inContext:self.context];

    
    NSError *error = nil;
    [theFetchedResultsController performFetch:&error];
    theFetchedResultsController.delegate = self;
    self.fetchedResultsController = theFetchedResultsController;
    
    // Listen for this notification so that the managedObjectContext runs on the main thread
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(contextChanged:) name:NSManagedObjectContextDidSaveNotification object:nil];
    
    return _fetchedResultsController;
}

- (void)contextChanged:(NSNotification*)notification
{
    DLog(@"contextChanged");
    NSManagedObjectContext *context = [notification object];
    if ([context isEqual:self.context]) {
        DLog(@"same context");
        
        return;
    }else{
        DLog(@"different context");
    }
}
```

This is the output for the first time the app is ran when I get a blank tableview:

```
2015-01-22 12:13:48.327 alamode[42623:2687764] -[PostsViewController contextChanged:] [Line 92] contextChanged
2015-01-22 12:13:48.327 alamode[42623:2687764] -[PostsViewController contextChanged:] [Line 99] different context
2015-01-22 12:13:48.329 alamode[42623:2687763] -[PostsViewController contextChanged:] [Line 92] contextChanged
2015-01-22 12:13:48.329 alamode[42623:2687763] -[PostsViewController contextChanged:] [Line 99] different context

```

**Comment by Alydyn** [comment] 2015-01-22 20:26
It won't "save up to the MR_defaultContext" because they are sibling contexts. It looks like this:
![screen shot 2015-01-22 at 2 17 48 pm](https://cloud.githubusercontent.com/assets/4280700/5863768/82fd7ad6-a241-11e4-8e04-24b71db07b2d.png)

MagicalRecord automatically sets up `MR_defaultContext` to observe save notifications from `MR_rootSavingContext`.  Your method will NEVER log "same context" the way you expect because, again, they are not parent/child MOC's but rather sibling contexts.  In this scenario `MR_defaultContext` is not actually saving but rather merging the save changes notification from `MR_rootSavingContext`.

Check on StackOverflow.  There are numerous issues regarding this, as well as closed issues here.  Also try grabbing the newest release right from the release tab to make sure that have the latest.  It should be 2.3beta5.  There was a bug in earlier betas where the default context would not merge changes.

Also, out of curiosity, what happens if you re-fetch in the else?

```objC
- (void)contextChanged:(NSNotification*)notification
{
    DLog(@"contextChanged");
    NSManagedObjectContext *context = [notification object];
    if ([context isEqual:self.context]) {
        DLog(@"same context");

        return;
    }else{
        DLog(@"different context");
        [self.fetchedResultsController performFetch:nil]; // add this
    }
}

```

**Comment by travisjbeck** [comment] 2015-01-22 22:02
Yeah, Im using 2.3.0-beta.5
If I add that line.  The App hangs indefinitely.  
If MR_defaultContext never gets notified of a change how will this EVER work?  
Am I setting the FRC up wrong? Am I saving my data wrong?

Theres obviously something I'm missing, I've done this exact same thing dozens of times before and never had this problem.

**Comment by Alydyn** [comment] 2015-01-23 01:35
Have you turned on core data concurrency debugging?

**Comment by travisjbeck** [comment] 2015-01-23 01:44
Not sure what that is.

**Comment by Alydyn** [comment] 2015-01-23 12:52
http://oleb.net/blog/2014/06/core-data-concurrency-debugging/

**Comment by travisjbeck** [comment] 2015-01-23 14:34
When I add that it crashes after:

```
2015-01-23 08:29:38.602 alamode[54708:3776337] → Saving <NSManagedObjectContext (0x7ff9fb6059e0): MagicalRecord Default Context> on the main thread
2015-01-23 08:29:38.602 alamode[54708:3776337] → Save Parents? YES
2015-01-23 08:29:38.602 alamode[54708:3776337] → Save Synchronously? YES
```

On this line 105 in NSManagedObjectContext+MagicalRecord.m:

```
- (NSString *) MR_workingName
{
    NSString *workingName = [[self userInfo] objectForKey:MagicalRecordContextWorkingName];//Crashes here

    if ([workingName length] == 0)
    {
        workingName = @"Untitled Context";
    }

    return workingName;
}


```

**Comment by Alydyn** [comment] 2015-01-23 15:09
You'll need to modify the `MR_setWorkingName:`
```objC
- (void) MR_setWorkingName:(NSString *)workingName
{
    [self performBlockAndWait:^{
        [[self userInfo] setObject:workingName forKey:MagicalRecordContextWorkingName];
    }];
}

```

**Comment by travisjbeck** [comment] 2015-01-23 18:36
Still hangs on the same line

**Comment by Alydyn** [comment] 2015-01-23 18:48
Then you are most likely accessing the context on the wrong queue.  Wrap
you access in `-performBlock:` and `-performBlockAndWait:`

**Comment by travisjbeck** [comment] 2015-01-23 19:10
Sorry for my ignorance Aldyn, could you elaborate?

**Comment by Alydyn** [comment] 2015-01-23 22:07
This is a really hard issue to troubleshoot because I feel like there is something else going on, specifically with respect to contexts or how you have set up your model/contexts.  Generally speaking in my experience when you have a "hang" it is because you have a context waiting on something to happen somewhere else, which for me was caused by concurrency violations.  Turning on concurrency debugging as outlined in that link is the first step.  (And verify that it is indeed "hanging" and not throwing the concurrency violation exception).

Next I highly recommend starting simple and adding complexity.  Create your `NSFetchedResultsController` with NO predicate, execute the fetch, and then add and save new objects but this time use the same context as the FRC (`MR_defaultContext`).  When you verify that it works as intended, then add in the background context, but do it with only a few inserts, and try setting breakpoints in your `-contextChanged:` method to verify that the objects are what you expect.

If none of that works then the only suggestion I have left is to make a simple project that reproduces your issue and I can take a look at it.

**Comment by travisjbeck** [comment] 2015-01-23 23:44
I finally figured it out.  Thank you Alydyn for leading me down the right path.  It was my predicate.

**Comment by Alydyn** [comment] 2015-01-24 00:12
Glad to help.  Can you close this issue then?  Thanks!

**Closed** 2015-01-24 00:16 UTC
