### ISSUE TITLE
saveWithBlock returns with success==NO and error==nil

### ISSUE THREAD

**Issue by seboslaw** [magicalpanda/MagicalRecord#939] opened 2015-01-07 19:42 UTC
Hey,

I'm having trouble with the saveWithBlock method. I have a download manager for tracks. When those fail to download I increase a "downloadTries" value for each track and re-try the download until "downloadTries" exceeds a certain value.

```
-(void) downloadDidFailForTrack:(Track*)track;
{
    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
      Track *localTrack = [track MR_inContext:localContext];
        if(track.downloadTriesValue < 3){
            //increment
            localTrack.downloadTriesValue++;
        } else{
            [self removeTrackFromQueue:localTrack];
        }
    } completion:^(BOOL success, NSError *error) {
      if (!success || error) {
          NSLog(@"why is this happing to me???");
      }
      if (track.downloadTriesValue < 3) {
          [self performDownloadOfTrack:track];
      }
    }];
}
```

As you see the track's downloadTries value gets updated in the background. In the completion block I call the download function again (which may result in a callback to this function ultimately).
Since I'm doing my downloads async (with NSURLSessions) this function downloadDidFailForTrack will be called for a lot of tracks in parallel. 

The problem I have is that if implemented as above success == NO in the completion block for some reason. In the log I find a lot of 

```
NO CHANGES IN ** BACKGROUND SAVING (ROOT) ** CONTEXT - NOT SAVING
```

lines popping up. Upon further investigation I found out that the "localTrack" I create within the saveWithBock block always gets the vanilla version from the database that still says "downloadTriesValue==0". So somehow the main context never gets saved, but why?

**Comment by Alydyn** [comment] 2015-01-07 21:48
As noted in the logs, you'll get `!success || !error` if there are no changes to the context that need to be saved.  

Is `.downloadTriesValue` a transient property or persisted property?  If it is transient, that could cause what you are seeing.

Also, why do you need to do it this way?  Couldn't you combine all of this into one?  Note you may need to call `-removeTrackFromQueue:` on main thread, depending on your implementation, since the completion block is called on the main thread.

```obj-c
[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
      Track *localTrack = [track MR_inContext:localContext];
        if(++track.downloadTriesValue < 3){
          [self performDownloadOfTrack:track];
        } else{
           [self removeTrackFromQueue:localTrack];
        }
    }];
```

**Comment by Alydyn** [comment] 2015-01-07 21:50
I should also point out that you should check that the value of `track` is what you expect when it is in the completion block.  You do not mention what context is used to create that object, so it may not be getting updated values when you save the `localTrack` with updated `downloadTriesValue`.

**Comment by xjli1972** [comment] 2015-01-07 23:37
Your problem is due to data fault mechanism in Core Data. When you have these background contexts and threads, Core Data will somehow turn into data fault state, when that happens, your first if(track.downloadTriesValue < 3) condition will fail in saveWithBlock call, so incremental in localTrack.downloadTriesValue will be done, leading to "NOT SAVING" message.

You need to manually force fire fault by adding [track willAccessValueForKey:nil]; before both of your if(track.downloadTriesValue < 3) check so the track object got turned into full object. The following link has some details on why this can happen:

http://www.mlsite.net/blog/?p=518

I was able to reproduce your failure and got fixed by adding [track willAccessValueForKey:nil]; in the two places as mentioned above. To be safe, you should also refetch the track object before firing the fault command [track willAccessValueForKey:nil];, in this way, you are guaranteed to get the latest changes done by the localTrack object. And also, to refetch track object inside block, you need to define __block Track *newTrack = track; at the beginning of your downloadDidFailForTrack function call.  

![screen shot 2015-01-07 at 3 33 43 pm](https://cloud.githubusercontent.com/assets/6088416/5655447/1a762a90-9683-11e4-8281-75fab3f5d90c.png)

![screen shot 2015-01-07 at 3 35 12 pm](https://cloud.githubusercontent.com/assets/6088416/5655448/1e3416c4-9683-11e4-8a92-82807fc07538.png)

**Comment by xjli1972** [comment] 2015-01-07 23:39
Had a typo above: "so incremental in localTrack.downloadTriesValue will be done" should be "so incremental in localTrack.downloadTriesValue will NOT be done".

**Comment by Alydyn** [comment] 2015-01-08 14:39
@xjli1972 I would point out that the Apple docs specifically state that accessing a persistent property of an object is accessed the fault will fire automatically.  This is stated in both the `NSManagedObject` docs as well as the section "Faulting and Uniquing" in the "Core Data Programming Guide".

Hence my question to him regarding if the property is persisted or transient.

**Comment by seboslaw** [comment] 2015-01-14 14:15
Thanks to both of you!
@Alydyn "downloadTries" is indeed transient (took over this project from s.o. else; that's why I didn't see it before). Will your "combine all of this into one" method work with this value being transient?
@xjli1972 so by calling willAccessValueForKey:nil you trick CoreData into saving the object although it normally wouldn't (cause downloadTries is transient)?

**Comment by Alydyn** [comment] 2015-01-14 14:35
@seboslaw Core Data won't save the object because there is nothing to save.  Transient properties are not persisted by definition.
I'm fairly certain my suggestion won't work for a transient property, as you currently have it implemented.  Honestly I think you should change this implementation to use `NSOperation` and `NSOperationQueue` anyway.  It's perfect for this use case.

**Comment by seboslaw** [comment] 2015-01-14 15:01
@Alydyn you're right. of course it won't save. was about to try the implementation out when it hit me :)
About nsoperationqueue. That's the way it was before. it's a simple download manager for files. before everything went through an nsoperationqueue which scheduled the downloads. 
however, i'm currently changing the implementation to a NSURLSessionDownloadTask implementation so that those downloads run the background. so i basically only need CoreData to do some book-keeping and persist the changes that those background tasks produce.

**Comment by Alydyn** [comment] 2015-01-14 15:05
Is there any reason you cannot change `downloadTriesValue` to be persistent?  Then in your success handler you could change it's value to something that makes sense or reset it to 0.

**Comment by seboslaw** [comment] 2015-01-14 15:08
not really....also thinking about it right now ;)
Thanks a lot for your input! Helped me lots!!!!

**Comment by Alydyn** [comment] 2015-01-14 15:10
@seboslaw no problem, good luck!

**Closed** 2015-01-14 15:12 UTC

**Comment by jhoughjr** [comment] 2015-12-12 01:11
I am experiencing this issue on normal non transient properties.
