### ISSUE TITLE
compile error with Undefined symbols

### ISSUE THREAD

**Issue by feefly1987** [magicalpanda/MagicalRecord#1151] opened 2015-12-14 07:22 UTC
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in MagicalRecord+ErrorHandling.o
      objc-class-ref in NSManagedObject+MagicalDataImport.o
      objc-class-ref in NSManagedObject+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalObserving.o
      objc-class-ref in NSManagedObjectContext+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalSaves.o
      objc-class-ref in NSObject+MagicalDataImport.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by feefly1987** [comment] 2015-12-14 07:25
I add CocoaLumberjack support with Swift like this in podfile:
pod 'CocoaLumberjack/Swift', '~> 2.2.0'

then compile error with Undefined symbols

**Comment by tonyarnold** [comment] 2016-01-23 02:48
Duplicate of #988.

**Closed by tonyarnold** 2016-01-23 02:48 UTC
