### ISSUE TITLE
'MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h' file not found

### ISSUE THREAD

**Issue by ryanjm** [magicalpanda/MagicalRecord#1095] opened 2015-09-23 23:47 UTC
I just updated my version of MagicalRecord, using the latest code off of the `develop` branch. I'm getting the following error:

```
In file included from /Users/ryanjm/code/iphone-app/Prefix.pch:41:
/Users/ryanjm/code/iphone-app/MagicalRecord/MagicalRecord.h:17:9: fatal error: 'MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h' file not found
#import <MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h>
        ^
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

I see the file there but Xcode 7 isn't finding it. Any ideas what I can do to make sure it finds the file and links everything properly? Thanks!

**Comment by Collibhoy** [comment] 2016-02-21 19:32
Did you ever resolve this?  I am having the same error.

**Comment by ryanjm** [comment] 2016-02-21 20:43
Sorry @Collibhoy I don't remember what I did. Have you tried clearing derived data?

**Comment by murthy8** [comment] 2016-03-03 06:28
@Collibhoy i have a small doubt.  i am importing magicalrecord sdk 2.3.3 in my xcode7 project.. means copy the magicalrecord items in my project. i am not using cocoapods.. i got one issue.. i.e. "MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h file not found in xcode7" how to solve the issue??  the issue is getting from "NSAttributeDescription+MagicalDataImport.h" file...

**Comment by murthy8** [comment] 2016-03-03 06:35
@ryanjm hi if u have any idea plz tell me

**Comment by gunesmert** [comment] 2016-03-07 14:56
What cocoapods version are you guys using? I was using 0.39.0, and was not facing this issue. But when I upgraded cocoapods to version 1.0.0.beta.4, I started facing with this problem. And I downgraded it to 0.39.0 again.

**Comment by murthy8** [comment] 2016-03-15 12:52
@gunesmert  i have small doubt.. i was integrating Magical Record sdk 2.3.2.. it is integrated successfully. but i have some errors. i.e. "mr_contextforcurrentthread deprecated in magicalrecord 3.0".. so how to fix this issue. plz guide me

**Comment by gunesmert** [comment] 2016-03-15 12:55
@murthy8 cleaning DerivedData and re-building the application with Cocoapods version 1.0.0.beta.4 worked for me.

**Comment by murthy8** [comment] 2016-03-15 13:07
@gunesmert  i got warning messages. nearly 300 plus warning messages like this "mr_contextforcurrentthread deprecated in magicalrecord 3.0"

**Comment by gunesmert** [comment] 2016-03-15 13:10
I have no idea mate. I have no warnings. Why don't you try adding it via Cocoapods?

**Comment by murthy8** [comment] 2016-03-15 13:12
@gunesmert  i am adding magical record through cocoapods

**Comment by gunesmert** [comment] 2016-03-15 13:14
In what version?

**Comment by murthy8** [comment] 2016-03-15 13:22
@gunesmert cocoapods version number is:  0.39.0

**Comment by gunesmert** [comment] 2016-03-15 13:24
Can you try upgrading to beta versions of Cocoapods?

$ [sudo] gem install cocoapods --pre

There are no problems with version 1.0.0.beta.4

**Comment by murthy8** [comment] 2016-03-17 11:04
@gunesmert  last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance...

**Comment by murthy8** [comment] 2016-03-21 05:58
@gunesmert   last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance... plz give me your guidance.. it is on demand to update.. Thank you.....

**Comment by murthy8** [comment] 2016-03-21 06:11
@ryanjm   last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance... plz give me your guidance.. it is on demand to update.. Thank you.....

**Comment by murthy8** [comment] 2016-03-21 07:59
@Collibhoy   last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance... plz give me your guidance.. it is on demand to update.. Thank you.....

**Comment by ryanjm** [comment] 2016-03-21 16:55
@murthy8 FYI: Your messages get sent to all participants in this issue (you can see the list on the right). Sending 4 exact messages ends up becoming spam in each of our inboxes. This is an open source project, the best you can expect is some direction in how to solve something. You'll need to explain what you've tried in order to get better help. Additionally, Stackoverflow is a good place to get direct help if you need that. These github issues are technically for bugs.

I haven't updated my version of MagicalRecord in awhile. I use my own [branch](https://github.com/ryanjm/MagicalRecord) and I add it directly to my project. You are free to try to use that branch, but know that it is out of date. It has been awhile since I've attempted to update MR using cocoapods as I've had issues with that in the past. Specifically I needed to overwrite some files to make the import code work.

I have recently created my own library for the imports so I might be attempting to update to a newer version of MR soon, but that probably won't be for a week or two. At that point, I'll update this issue what what worked for me and if I needed to do anything to fix it.

**Comment by KarlJay** [comment] 2016-05-27 09:55
@ryanjm, thanks for your post!  It solved my problem.

**Comment by adamawolf** [comment] 2016-06-01 20:04
I started seeing this issue after upgrading Cocoapods to 1.0. 

As @gunesmert said above, Clearing Derived data fixed this issue for me.

**Comment by amleszk** [comment] 2016-07-12 21:14
I also saw this in Cocoapods 1.x and seemed to be fixed this by editing file: `MagicalRecord+ShorthandMethods.h`

Remove line: `#import <MagicalRecord/MagicalRecord.h>`

**Comment by Coeur** [comment] 2019-10-28 13:54
Please note that nowadays I will only consider issues with CocoaPods 1.7.5 or newer.

There are no issues on develop branch (MagicalRecord 2.4.0), as seen by the Travis builds.
But if you do have an issue and if the fix is about modifying an import statement, then please make a pull request and show me that it passes the Travis builds.

For now, I'm closing it as "Can't reproduce".

**Closed by Coeur** 2019-10-28 13:54 UTC
