### ISSUE TITLE
use_frameworks! causes error: include of non-modular header inside framework module 'MagicalRecord.MagicalRecord_ShorthandMethods'

### ISSUE THREAD

**Issue by elviin** [magicalpanda/MagicalRecord#1276] opened 2016-11-29 09:47 UTC
I use cocapods v1.1.1.  Using MagicalRecord (2.3.2)
I have already in my Podfile **pod 'MagicalRecord'**. In the file I have also added use_frameworks! instruction and also the library **pod 'Socket.IO-Client-Swift'**.

The Swift library requires using **use_frameworks!** in the Podfile. 

When building I get the errors:

`    While building module 'MagicalRecord' imported from     .../MagicalRecord/MagicalRecord.framework/Headers/NSManagedObjectContext+MagicalSaves.h:10:

    .../Build/Products/Debug-iphonesimulator/MagicalRecord/MagicalRecord.framework/Headers/MagicalRecord+ShorthandMethods.h:4:9: error: include of non-modular header inside framework module 'MagicalRecord.MagicalRecord_ShorthandMethods' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <MagicalRecord/MagicalRecord.h>

    .../Build/Products/Debug-iphonesimulator/MagicalRecord/MagicalRecord.framework/Headers/NSManagedObjectContext+MagicalSaves.h:10:9: fatal error: could not build module 'MagicalRecord'
#import <MagicalRecord/MagicalRecordDeprecationMacros.h>
     ~~~~~~~^
    2 errors generated.
`

**Comment by amleszk** [comment] 2016-12-27 16:58
Related to closed issue: https://github.com/CocoaPods/CocoaPods/issues/4420

**Comment by Coeur** [comment] 2019-05-30 06:41
@amleszk that issue was marked as resolved in CocoaPods 1.0.0, but elviin was using CocoaPods 1.1.1.

I'll try to see if I reproduce the issue nowadays (CocoaPods 1.6.2 +) or not.

**Comment by Coeur** [comment] 2019-05-30 06:56
I took the objective-c MagicalRecordRecipes sample from the project:
- I removed the reference to the vendor folder.
- `pod init` with CocoaPods 1.7.0
- I added the following to the Podfile:
```ruby
  use_frameworks!
  pod 'MagicalRecord', :path => '../..'
  pod 'Socket.IO-Client-Swift'
```
- `pod install`

=> I only got some deprecation warnings, no building error related to MagicalRecord.

**Comment by Coeur** [comment] 2019-05-30 07:26
I'll apply a minor import improvement in #1350 for next release. But as I can't reproduce your issue, I'll close it.

**Closed by Coeur** 2019-05-30 07:26 UTC
