### ISSUE TITLE
Undefined symbols for architecture arm64:   _OBJC_CLASS_$_DDLog

### ISSUE THREAD

**Issue by elviin** [magicalpanda/MagicalRecord#1154] opened 2015-12-16 13:50 UTC
Podfile: (cocoapods-0.39.0)

    ...
    platform :ios, '8.0'

    pod 'MagicalRecord'
    pod 'CocoaLumberjack'

    use_frameworks!

Linker does not see Cocoalumberjack from Magical record:

        Ld /Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Products/Debug-iphoneos/MagicalRecord.framework/MagicalRecord normal arm64
        cd /Users/slavik/Documents/Development/workingCopy/ios/TipsportNet/Pods
        export IPHONEOS_DEPLOYMENT_TARGET=8.0
        export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Products/Debug-iphoneos -F/Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Products/Debug-iphoneos -filelist /Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Intermediates/Pods.build/Debug-iphoneos/MagicalRecord.build/Objects-normal/arm64/MagicalRecord.LinkFileList -install_name @rpath/MagicalRecord.framework/MagicalRecord -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -fembed-bitcode-marker -framework CoreData -fobjc-arc -fobjc-link-runtime -framework CoreData -framework Foundation -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Intermediates/Pods.build/Debug-iphoneos/MagicalRecord.build/Objects-normal/arm64/MagicalRecord_dependency_info.dat -o /Users/slavik/Library/Developer/Xcode/DerivedData/Tipsport-gkjfrochukajgydvlgybmwgvxpvw/Build/Products/Debug-iphoneos/MagicalRecord.framework/MagicalRecord

        Undefined symbols for architecture arm64:
        "_OBJC_CLASS_$_DDLog", referenced from:
        objc-class-ref in MagicalRecord+ErrorHandling.o
        objc-class-ref in NSManagedObject+MagicalDataImport.o
        objc-class-ref in NSManagedObject+MagicalRecord.o
        objc-class-ref in NSManagedObjectContext+MagicalObserving.o
        objc-class-ref in NSManagedObjectContext+MagicalRecord.o
        objc-class-ref in NSManagedObjectContext+MagicalSaves.o
        objc-class-ref in NSObject+MagicalDataImport.o
        ...
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by duhongliang** [comment] 2015-12-28 02:15
I have the same issure. And already can not resolve.

**Comment by elviin** [comment] 2015-12-28 11:03
@duhongliang  I had to add a recursive paths in the project settings> Project / Build Settings / All / type Header Search Path in the search field

Add the following lines in the box: $(PODS_ROOT)/MagicalRecord and make it recursive.

**Comment by danielgalasko** [comment] 2016-01-08 09:48
Looks like a duplicate of https://github.com/magicalpanda/MagicalRecord/issues/1116 and https://github.com/magicalpanda/MagicalRecord/issues/988

**Comment by tonyarnold** [comment] 2016-01-23 02:46
This is a duplicate of #988. I believe this issue is solved, but I don't use CocoaLumberjack so please let me know if it isn't.

**Closed by tonyarnold** 2016-01-23 02:46 UTC
